from PyQt5 import QtCore, QtGui, QtWidgets
import res


class Ui_ImaCon(object):
    def setupUi(self, ImaCon):
        ImaCon.setObjectName("ImaCon")
        ImaCon.resize(804, 592)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/images/Picture_24x24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ImaCon.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ImaCon)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.frame_3)
        self.convert_btn = QtWidgets.QPushButton(self.frame)
        self.convert_btn.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.convert_btn.setFont(font)
        self.convert_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convert_btn.setStyleSheet("background-color: rgb(0, 0, 255);\n"
                                       "color: rgb(255, 255, 255);\n"
                                       "border-radius: 25px;")
        self.convert_btn.setObjectName("convert_btn")
        self.verticalLayout.addWidget(self.convert_btn)
        self.horizontalLayout_4.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.thumbnail_label = QtWidgets.QLabel(self.groupBox)
        self.thumbnail_label.setMaximumSize(QtCore.QSize(300, 200))
        self.thumbnail_label.setText("")
        self.thumbnail_label.setPixmap(QtGui.QPixmap("image.jpg"))
        self.thumbnail_label.setScaledContents(True)
        self.thumbnail_label.setObjectName("thumbnail_label")
        self.horizontalLayout_2.addWidget(self.thumbnail_label)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.img_details_textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.img_details_textEdit.setFont(font)
        self.img_details_textEdit.setObjectName("img_details_textEdit")
        self.horizontalLayout_3.addWidget(self.img_details_textEdit)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addWidget(self.frame_2)
        ImaCon.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ImaCon)
        self.statusbar.setObjectName("statusbar")
        ImaCon.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(ImaCon)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        ImaCon.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd_Images = QtWidgets.QAction(ImaCon)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgs/images/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Images.setIcon(icon1)
        self.actionAdd_Images.setObjectName("actionAdd_Images")
        self.actionRemove_Selected = QtWidgets.QAction(ImaCon)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imgs/images/Remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_Selected.setIcon(icon2)
        self.actionRemove_Selected.setObjectName("actionRemove_Selected")
        self.actionRemove_All = QtWidgets.QAction(ImaCon)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imgs/images/Delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_All.setIcon(icon3)
        self.actionRemove_All.setObjectName("actionRemove_All")
        self.toolBar.addAction(self.actionAdd_Images)
        self.toolBar.addAction(self.actionRemove_Selected)
        self.toolBar.addAction(self.actionRemove_All)

        self.retranslateUi(ImaCon)
        QtCore.QMetaObject.connectSlotsByName(ImaCon)

    def retranslateUi(self, ImaCon):
        _translate = QtCore.QCoreApplication.translate
        ImaCon.setWindowTitle(_translate("ImaCon", "ImaCon"))
        self.label.setText(_translate("ImaCon", "Output Format"))
        self.comboBox.setItemText(1, _translate("ImaCon", "jpg"))
        self.comboBox.setItemText(2, _translate("ImaCon", "png"))
        self.comboBox.setItemText(3, _translate("ImaCon", "tiff"))
        self.comboBox.setItemText(4, _translate("ImaCon", "ico"))
        self.comboBox.setItemText(5, _translate("ImaCon", "gif"))
        self.comboBox.setItemText(6, _translate("ImaCon", "jpeg"))
        self.comboBox.setItemText(7, _translate("ImaCon", "bmp"))
        self.comboBox.setItemText(8, _translate("ImaCon", "webp"))
        self.convert_btn.setText(_translate("ImaCon", "Convert Images"))
        self.groupBox.setTitle(_translate("ImaCon", "Image"))
        self.groupBox_2.setTitle(_translate("ImaCon", "Image Details"))
        self.toolBar.setWindowTitle(_translate("ImaCon", "toolBar"))
        self.actionAdd_Images.setText(_translate("ImaCon", "Add Images"))
        self.actionAdd_Images.setShortcut(_translate("ImaCon", "Ctrl+O"))
        self.actionRemove_Selected.setText(_translate("ImaCon", "Remove Selected"))
        self.actionRemove_Selected.setShortcut(_translate("ImaCon", "Del"))
        self.actionRemove_All.setText(_translate("ImaCon", "Remove All"))
        self.actionRemove_All.setShortcut(_translate("ImaCon", "Alt+Del"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ImaCon = QtWidgets.QMainWindow()
    ui = Ui_ImaCon()
    ui.setupUi(ImaCon)
    ImaCon.show()
    sys.exit(app.exec_())
